{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /login_safe (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BD78A24D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","children":[{"name":"加密接口-正确的用户名和密码","uid":"79652414956fd36","parentUid":"1040b52cf7db20e1b59826456f66846c","status":"broken","time":{"start":1728414501058,"stop":1728414503204,"duration":2146},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["''"],"tags":[]}],"uid":"1040b52cf7db20e1b59826456f66846c"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /login_safe (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BD7BA4250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","children":[{"name":"加密接口-错误的用户名和密码","uid":"56991eb67b28e2e1","parentUid":"d881fbe675245af965c19bb6c81017ee","status":"broken","time":{"start":1728414503603,"stop":1728414505639,"duration":2036},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["''"],"tags":[]}],"uid":"d881fbe675245af965c19bb6c81017ee"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}